version: '3'
services:
  master:
    container_name: redis-master-6379
    image: redis
    privileged: true
    volumes:
      - ./conf/:/conf/
    command: ["redis-server", "/conf/redis-6379.conf"]

  slave-1:
    container_name: redis-slave-6380
    image: redis
    privileged: true
    network_mode: "container:redis-master-6379"
    volumes:
      - ./conf/:/conf/
    command: ["redis-server", "/conf/redis-6380.conf"]
    depends_on: 
      - master

  slave-2:
    container_name: redis-slave-6381
    image: redis
    privileged: true
    network_mode: "container:redis-master-6379"
    volumes:
      - ./conf/:/conf/
    command: ["redis-server", "/conf/redis-6381.conf"]
    depends_on: 
      - master


  sentinel-1:
    container_name: redis-sentinel-26379
    image: redis
    privileged: true
    network_mode: "container:redis-master-6379"
    volumes:
      - ./conf/:/conf/
    command: ["redis-sentinel", "/conf/sentinel-26379.conf"]
    depends_on: 
      - master

  sentinel-2:
    container_name: redis-sentinel-26380
    image: redis
    privileged: true
    network_mode: "container:redis-master-6379"
    volumes:
      - ./conf/:/conf/
    command: ["redis-sentinel", "/conf/sentinel-26380.conf"]
    depends_on: 
      - master

  sentinel-3:
    container_name: redis-sentinel-26381
    image: redis
    privileged: true
    network_mode: "container:redis-master-6379"
    volumes:
      - ./conf/:/conf/
    command: ["redis-sentinel", "/conf/sentinel-26381.conf"]
    depends_on: 
      - master